/**
 * This class has been generated by Fast Code Eclipse Plugin 
 * For more information please go to http://fast-code.sourceforge.net/
 * @author : ravikant
 * Created : 12/16/2018 02:22:33
 */

package com.chanikya.learing.springframework.sfgpetclinic.services.map;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNull;

import java.util.Set;

import org.junit.Before;
import org.junit.Test;

import com.chanikya.learing.springframework.sfgpetclinic.model.Owner;

public class OwnerMapServiceTest {
	Long ownerId = 1L;

	OwnerMapService ownerMapService;

	@Before
	public void setUp() throws Exception {
		// TODO add setup code.
		ownerMapService = new OwnerMapService(new PetTypeMapService(), new PetMapService());
		ownerMapService.save(Owner.builder().id(ownerId).lastName("mamillapalli").build());
	}

	/**
	 *
	 * @see com.chanikya.learing.springframework.sfgpetclinic.services.map.OwnerMapService#findAll()
	 */
	@Test
	public void findAll() {
		Set<Owner> all = ownerMapService.findAll();
		assertEquals(1, all.size());
	}

	/**
	 *
	 * @see com.chanikya.learing.springframework.sfgpetclinic.services.map.OwnerMapService#findById(Long)
	 */
	@Test
	public void findById() {
		Owner byid = ownerMapService.findById(ownerId);
		assertEquals(ownerId, byid.getId());
	}

	/**
	 *
	 * @see com.chanikya.learing.springframework.sfgpetclinic.services.map.OwnerMapService#save(Owner)
	 */
	@Test
	public void save() {
		Long Owner2Id = 2L;
		Owner object = Owner.builder().id(Owner2Id).build();
		Owner result = ownerMapService.save(object);
		assertEquals(Owner2Id, result.getId());
	}

	/**
	 *
	 * @see com.chanikya.learing.springframework.sfgpetclinic.services.map.OwnerMapService#deleteById(Long)
	 */
	@Test
	public void deleteById() {
		Long Owner2Id = 2L;
		ownerMapService.deleteById(Owner2Id);
		assertNull(ownerMapService.findById(Owner2Id));
	}

	/**
	 *
	 * @see com.chanikya.learing.springframework.sfgpetclinic.services.map.OwnerMapService#findByLastname(String)
	 */
	@Test
	public void findByLastname() {

		Owner bylastname = ownerMapService.findByLastname("mamillapalli");
		assertEquals("mamillapalli", bylastname.getLastName());
	}

	/**
	 *
	 * @see com.chanikya.learing.springframework.sfgpetclinic.services.map.OwnerMapService#delete(Owner)
	 */
	@Test
	public void delete() {
		// Owner object = new Owner();
		ownerMapService.delete(ownerMapService.findById(ownerId));
		assertEquals(0, ownerMapService.findAll().size());
	}

}
